# Generated by Django 3.2.3 on 2021-05-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='names',
            new_name='name',
        ),
    ]
